// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toeopohyimvnecsguzgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZW9wb2h5aW12bmVjc2d1emdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzUxMzUsImV4cCI6MjA2MjkxMTEzNX0.-BxjvXPOzfesCOSb92Ul2o0-GAZz6eu086SEsMfFCOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);